; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Locura Instantánea"
#define MyAppVersion "1.0"
#define MyAppPublisher "Eduardo Lau"
#define MyAppURL "https://github.com/Eduardo-Lau"
#define MyAppExeName "Locura_Instantanea.exe"
#define MyAppAssocName "executable File"
#define MyAppAssocExt ".exe"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#include ReadReg(HKLM, 'Software\WOW6432Node\Mitrich Software\Inno Download Plugin', 'InstallDir') + '\idp.iss'

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BEB54011-F3BB-4B93-BB16-11C2D95E327D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={userappdata}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=admin
OutputDir=C:\Users\carlo\OneDrive - Facultad de Ingeniería de la Universidad de San Carlos de Guatemala\USAC\Anterior\PROGRA\MC2\Locura_Inst\res
OutputBaseFilename=Locura_Instantanea_Setup
SetupIconFile=C:\Users\carlo\Downloads\Locura_Instantanea\app\Binarios\LogoLi.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\carlo\OneDrive - Facultad de Ingeniería de la Universidad de San Carlos de Guatemala\USAC\Anterior\PROGRA\MC2\Locura_Inst\app\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\carlo\OneDrive - Facultad de Ingeniería de la Universidad de San Carlos de Guatemala\USAC\Anterior\PROGRA\MC2\Locura_Inst\res\*"; DestDir: "{app}"; AfterInstall: InstalarJDK; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files


[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent;
Filename: "{cmd}"; Parameters: "/C del ""{app}\jdk-17_windows-x64_bin.exe"""; Flags: runhidden

[Code]
procedure InstalarJDK;
var
  ResultCode: Integer;
  JDKInstalled: Boolean;
  JavaInstallerURL : String;
begin
  // Verificar si la clave de registro correspondiente al JDK existe
  JDKInstalled := RegKeyExists(HKLM64, 'SOFTWARE\JavaSoft\JDK');

  if not JDKInstalled then
  begin
  JDKInstalled := RegKeyExists(HKLM32, 'SOFTWARE\JavaSoft\JDK');
  end;

  if not JDKInstalled then
  begin
    // JDK no está instalado, proceder con la instalación
    JavaInstallerURL := 'https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe'; // URL del instalador
    idpAddFile(JavaInstallerURL, ExpandConstant('{app}\jdk-17_windows-x64_bin.exe'));
    idpDownloadFiles;
    while not FileExists(ExpandConstant('{app}\jdk-17_windows-x64_bin.exe')) do
    begin

    Sleep(1000); // Puedes ajustar el intervalo de espera según tus necesidades
    end;

    if not Exec(ExpandConstant('{app}\jdk-17_windows-x64_bin.exe'), '/s', ''
      , SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode)
    then
      MsgBox('¡El instalador del JDK falló!' + #13#10 +
        SysErrorMessage(ResultCode), mbError, MB_OK);
  end;
  
end;


