
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


@background = #1E1F22
@componentBackground = lighten(@background,5%)
ComboBox.background = lighten(@background,10%)
@accentColor = #8792FF