
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


@background = #1E1F22
ComboBox.background = darken(over(@nsControlColor,@background),5%)
@accentColor = #7784FF